---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: kraken-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - sway #Sway
        - wl-clipboard #Sway dependencie
        - waybar #Sway dependencie
        - miko #Sway dependencie
        - light #Sway dependencie
        - mpd #Sway dependencie
        - mpv #Sway dependencie
        - ncmpcpp #Sway dependencie
        - ranger #Sway dependencie
        - wofi #Sway dependencie
        - swaylock #Sway dependencie
        - kitty #Sway dependencie
        - maim #Sway dependencie
        - grim #Sway dependencie
        - slurp #Sway dependencie
        - swayidle #Sway dependencie
        - gdm #Sway dependencie
        - starship
        - wofi
        - tailscale
        - fastfetch
        - alacritty
        - mesa-dri-drivers
        - mesa-vulkan-drivers
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - @kde-desktop
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - com.github.marhkb.Pods
          - io.github.flattool.Warehouse
          - com.github.tchx84.Flatseal
          - com.dec05eba.gpu_screen_recorder
          - io.github.ilya_zlobintsev.LACT
          - io.github.kolunmi.Bazaar
          - org.onlyoffice.desktopeditors
          - org.kde.kdenlive
          - org.kde.okular
          - org.kde.dolphin
          - org.kde.filelight
          - org.fedoraproject.MediaWriter
          - org.kde.kate
          - dev.deedles.Trayscale
          - com.vivaldi.Vivaldi
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
